version: "3.11"

services:
  mockup-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    networks:
      - default

  proxy:
    build: ./proxy
    ports:
      - 8181:8181
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - default 
  
networks:
  default:
    driver: bridge